"""
Django settings for ms_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from neomodel import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h@%xufa+u=)edj)%zf4gco3ni^s&%*e&^m!%f1r69ggh^+n34f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ms_user_social.apps.MsUserSocialConfig',
    'django_neomodel',
    'neomodel'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ms_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ms_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'neomodel.util.Database',
#         'NAME': os.environ.get('NEO4J_DATABASE_NAME'),
#         'USER': os.environ.get('NEO4J_USER'),
#         'PASSWORD': os.environ.get('NEO4J_PASSWORD'),
#         'HOST': os.environ.get('NEO4J_HOST'),
#         'PORT': os.environ.get('NEO4J_PORT'),
#     }
# }

# NEO4J_USER = os.environ.get('NEO4J_USER')
# NEO4J_PASSWORD = os.environ.get('NEO4J_PASSWORD')
# NEO4J_HOST = os.environ.get('NEO4J_HOST')
# NEO4J_PORT = os.environ.get('NEO4J_PORT')

# # URL de conexión para Neo4j con variables de entorno
# NEO4J_BOLT_URL = f'neo4j://{NEO4J_USER}:{NEO4J_PASSWORD}@{NEO4J_HOST}:{NEO4J_PORT}'

# NEOMODEL_NEO4J_BOLT_URL = NEO4J_BOLT_URL

#NEOMODEL_NEO4J_URL = os.environ.get('NEO4J_URL','bolt://neo4j:password@localhost:7687')
#neo4j+s://521bcf7e.databases.neo4j.io

user = 'neo4j'
psw = 'BBzNUsMOMEMJN1Ihvs8OWjJPKOjkzi5snyalnLhhwoo'
uri = '25bd75f8.databases.neo4j.io:7687'
    
NEOMODEL_NEO4J_BOLT_URL = 'neo4j+s://{}:{}@{}'.format(user, psw, uri)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

#DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
