version: '3'

services:
  db:
    image: neo4j:5.17.0-community
    container_name: db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password

  api:
    build:
      context: ./ms_usersocial
      dockerfile: ./Dockerfile  
    ports:
      - "8000:8000"
    environment:
      - NEO4J_HOST=host.docker.internal
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
